
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class cardRatio : Luban.BeanBase
{
    public cardRatio(JSONNode _buf) 
    {
        { if(!_buf["round"].IsNumber) { throw new SerializationException(); }  Round = _buf["round"]; }
        { if(!_buf["white"].IsNumber) { throw new SerializationException(); }  White = _buf["white"]; }
        { if(!_buf["blue"].IsNumber) { throw new SerializationException(); }  Blue = _buf["blue"]; }
        { if(!_buf["purple"].IsNumber) { throw new SerializationException(); }  Purple = _buf["purple"]; }
        { if(!_buf["orange"].IsNumber) { throw new SerializationException(); }  Orange = _buf["orange"]; }
    }

    public static cardRatio DeserializecardRatio(JSONNode _buf)
    {
        return new cardRatio(_buf);
    }

    /// <summary>
    /// 轮次
    /// </summary>
    public readonly int Round;
    /// <summary>
    /// 白卡
    /// </summary>
    public readonly float White;
    /// <summary>
    /// 蓝卡
    /// </summary>
    public readonly float Blue;
    /// <summary>
    /// 紫卡
    /// </summary>
    public readonly float Purple;
    /// <summary>
    /// 橙卡
    /// </summary>
    public readonly float Orange;
   
    public const int __ID__ = -257601829;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "round:" + Round + ","
        + "white:" + White + ","
        + "blue:" + Blue + ","
        + "purple:" + Purple + ","
        + "orange:" + Orange + ","
        + "}";
    }
}

}
