
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class cardBase : Luban.BeanBase
{
    public cardBase(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["res_Img"].IsString) { throw new SerializationException(); }  ResImg = _buf["res_Img"]; }
        { if(!_buf["white_point"].IsNumber) { throw new SerializationException(); }  WhitePoint = _buf["white_point"]; }
        { if(!_buf["blue_point"].IsNumber) { throw new SerializationException(); }  BluePoint = _buf["blue_point"]; }
        { if(!_buf["purple_point"].IsNumber) { throw new SerializationException(); }  PurplePoint = _buf["purple_point"]; }
        { if(!_buf["orange_point"].IsNumber) { throw new SerializationException(); }  OrangePoint = _buf["orange_point"]; }
    }

    public static cardBase DeserializecardBase(JSONNode _buf)
    {
        return new cardBase(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 卡牌名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 图片资源
    /// </summary>
    public readonly string ResImg;
    /// <summary>
    /// 白卡分值
    /// </summary>
    public readonly int WhitePoint;
    /// <summary>
    /// 蓝卡分值
    /// </summary>
    public readonly int BluePoint;
    /// <summary>
    /// 紫卡分值
    /// </summary>
    public readonly int PurplePoint;
    /// <summary>
    /// 橙卡分值
    /// </summary>
    public readonly int OrangePoint;
   
    public const int __ID__ = -8786431;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "resImg:" + ResImg + ","
        + "whitePoint:" + WhitePoint + ","
        + "bluePoint:" + BluePoint + ","
        + "purplePoint:" + PurplePoint + ","
        + "orangePoint:" + OrangePoint + ","
        + "}";
    }
}

}
