
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbCardBase TbCardBase {get; }
    public TbCardRatio TbCardRatio {get; }
    public TbCardEffect TbCardEffect {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCardBase = new TbCardBase(loader("tbcardbase"));
        TbCardRatio = new TbCardRatio(loader("tbcardratio"));
        TbCardEffect = new TbCardEffect(loader("tbcardeffect"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCardBase.ResolveRef(this);
        TbCardRatio.ResolveRef(this);
        TbCardEffect.ResolveRef(this);
    }
}

}
