
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardEffect
{
    private readonly System.Collections.Generic.Dictionary<int, cardEffect> _dataMap;
    private readonly System.Collections.Generic.List<cardEffect> _dataList;
    
    public TbCardEffect(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cardEffect>();
        _dataList = new System.Collections.Generic.List<cardEffect>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cardEffect _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cardEffect.DeserializecardEffect(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, cardEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<cardEffect> DataList => _dataList;

    public cardEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cardEffect Get(int key) => _dataMap[key];
    public cardEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

