
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbCardBase
{
    private readonly System.Collections.Generic.Dictionary<int, cardBase> _dataMap;
    private readonly System.Collections.Generic.List<cardBase> _dataList;
    
    public TbCardBase(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, cardBase>();
        _dataList = new System.Collections.Generic.List<cardBase>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            cardBase _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = cardBase.DeserializecardBase(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, cardBase> DataMap => _dataMap;
    public System.Collections.Generic.List<cardBase> DataList => _dataList;

    public cardBase GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cardBase Get(int key) => _dataMap[key];
    public cardBase this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

